### ISSUE TITLE
Error (solved)

### ISSUE THREAD

**Issue by treksis** [victorchall/EveryDream#7]
Hi, this is the first time I see something with .parquet.
I cloned https://huggingface.co/datasets/laion/laion2B-en-aesthetic and manually copy and pasted 127 parquet files in laion folder. then ran downlaod_laion.py and I get this result. I need help

```
(venv) root@n8f6ytisqn:/notebooks/EveryDream# python scripts/download_laion.py --search_text "a man" --limit 50
Launching...
is running in venv: True
{Fore.CYAN}Unix detected, using default asyncio event loop policy{Style.RESET_ALL}
  Searching for a man in column: TEXT in ./laion//*.parquet
  reading file: ./laion/part-00051-9230b837-b1e0-4254-8b88-ed2976e9cee9-c000.snappy.parquet
Traceback (most recent call last):
  File "/notebooks/EveryDream/scripts/download_laion.py", line 322, in <module>
    result = asyncio.run(download_laion_matches(opt))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/notebooks/EveryDream/scripts/download_laion.py", line 274, in download_laion_matches
    df = pd.read_parquet(file, engine="auto")
  File "/notebooks/EveryDream/venv/lib/python3.9/site-packages/pandas/io/parquet.py", line 503, in read_parquet
    return impl.read(
  File "/notebooks/EveryDream/venv/lib/python3.9/site-packages/pandas/io/parquet.py", line 251, in read
    result = self.api.parquet.read_table(
  File "/notebooks/EveryDream/venv/lib/python3.9/site-packages/pyarrow/parquet/__init__.py", line 2780, in read_table
    dataset = _ParquetDatasetV2(
  File "/notebooks/EveryDream/venv/lib/python3.9/site-packages/pyarrow/parquet/__init__.py", line 2368, in __init__
    [fragment], schema=schema or fragment.physical_schema,
  File "pyarrow/_dataset.pyx", line 898, in pyarrow._dataset.Fragment.physical_schema.__get__
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Could not open Parquet input source '<Buffer>': Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.
```

**Comment by treksis** [comment]
sorry I think i messed up something with git lfs... will try to figure out.

**Comment by treksis** [comment]
solved. thanks for the genius work.
<img width="283" alt="image" src="https://user-images.githubusercontent.com/54779707/198184341-50bea547-fe31-41b1-921d-f9b47a06a3a8.png">

**Comment by victorchall** [comment]
/laion/*.parquet should be in the .gitignore and not impact git.  Glad you got it working.
